### ISSUE TITLE
feature request: add Hashable conformance to Benchmark.IterationValue

### ISSUE THREAD

**Issue by heckj** [ordo-one/package-histogram#9]
I was working with the internal values returned from Histogram, and it ended up being slightly awkward - specifically not easily being able to extend an internal type on a specialized version. Or... maybe I just don't know how to do that correctly, but in either case, I wanted to ask: Would there be any concern about making [Benchmark.IterationValue](https://github.com/ordo-one/package-histogram/blob/main/Sources/Histogram/Histogram.swift#L519) conform to `Hashable`?

It's internally conforming to Equatable already, but it would be extra lovely if I could safely drop it into a dictionary. At the moment, I'm working around this by mapping all the values into my own replica of that type, except that includes compiler-derived `Hashable` conformance.

I'd be happy to submit a PR to make the change.

**Comment by hassila** [comment]
Done in https://github.com/ordo-one/package-histogram/pull/11/commits/ccae3ccdddd0da14a391edd4285f660686cb5753
